# Introduction
- sandpit

# Import everything I nead :)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import LabelEncoder
from scipy.stats.stats import pearsonr

# Data Preparation

In [14]:
cancer = load_breast_cancer()
print(dir(cancer))
data = cancer.data
feat_names = cancer.feature_names
df_cancer = pd.DataFrame(data, columns=feat_names)
df_cancer.head(1)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0           0.1184   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0            0.2776          0.3001               0.1471         0.2419   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                   0.1189  

[1 rows x 30 columns]

In [15]:
path = './input/champs-scalar-coupling/train.csv'
df_train = pd.read_csv(path)
df_train.head(1)

id     molecule_name  atom_index_0  atom_index_1  type  \
0   0  dsgdb9nsd_000001             1             0  1JHC   

   scalar_coupling_constant  
0                   84.8076

# SandPit

In [17]:
df_train.shape

(4658147, 6)

In [18]:
df_train.groupby('type')['scalar_coupling_constant'].transform('mean').shape

(4658147,)

---
**LabelEncoder**

In [22]:
df_train['type_0'] = df_train['type'].apply(lambda x: x[0])
df_train['type_1'] = df_train['type'].apply(lambda x: x[1:])
df_train[['type', 'type_0', 'type_1']].head()

type type_0 type_1
0  1JHC      1    JHC
1  2JHH      2    JHH
2  2JHH      2    JHH
3  2JHH      2    JHH
4  1JHC      1    JHC

In [26]:
for f in ['type_0', 'type_1', 'type']:
    lbl = LabelEncoder()
    lbl.fit(list(df_train[f].values))
    df_train[f] = lbl.transform(list(df_train[f].values))

In [31]:
df_train[['type', 'type_0', 'type_1']].head()

type  type_0  type_1
0     0       0       0
1     3       1       1
2     3       1       1
3     3       1       1
4     0       0       0

In [33]:
df_train['type'].unique()

array([0, 3, 1, 4, 2, 6, 5, 7])

In [34]:
df_train['type_0'].unique()

array([0, 1, 2])

In [35]:
df_train['type_1'].unique()

array([0, 1, 2])

# v7-estimation-of...(download_code)